### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by gusarg81** [dieselburner/rcon-web#2]
Hi,

Actually, I want to use this rcon-web with Insurgency Sandstorm.

I've managed to run rcon-web with apache+proxy_uwscgi, login page shows. When I put the rcon password from my server, It just stays there loading in login page but nothings happens. No logs, no errors.

The rcon port in the game server is 27017, which I've added in rcon-web.conf (with rcon password as well).

Any tips? Thanks in advance.

**Comment by dieselburner** [comment]
Hi @gusarg81,

Which branch are you using? Master or v2? Master (v1 - old version) is python based, while v2 uses backend on Go, and I recommend that instead.

Tips for v1: if you change the configuration file, you need to restart backend app. Running it in standalone mode (not via Apache or Nginx) would help for debugging, since it would print some info into the terminal.

**Comment by gusarg81** [comment]
I was using master branch. Would be nice it to clarify in there. Let me test v2 and come back to you.

Note for master: logs was enabled; running via systemd. Also tested runing with uwsgi standalone too.

**Comment by dieselburner** [comment]
Regarding v2 - yes, the project was done a while ago and since there were no interest from community I didn't bother updating the docs. But I will do it now as soon as I have some spare time.

**Comment by gusarg81** [comment]
> Regarding v2 - yes, the project was done a while ago and since there were no interest from community I didn't bother updating the docs. But I will do it now as soon as I have some spare time.

Great!! Thanks.

**Comment by dieselburner** [comment]
Closing, since V1 in not maintaned anymore.
