### ISSUE TITLE
rcon-web exec in v2

### ISSUE THREAD

**Issue by gusarg81** [dieselburner/rcon-web#3]
Hi, install script in v2 brach makes referece to a executable file /srv/rcon-web/rcon-web but does not exist. Maybe should be rcon-web.go?

**Comment by dieselburner** [comment]
v2 is Golang based backend, which means it needs to be build. Execute `go build` in git root and then adjust `install` script to your paths. Please note, you need to copy files from `system` dir in git to appropriate places and restart services like syslogd, but if I recall correctly, script will do this for you, but I might be wrong (do not have access to source code at the moment). I will try to find some time tomorrow to prepare a documentation.

**Comment by gusarg81** [comment]
Right, sorry, never used Golang (I am Python developer).

I didnt used the script, Just doin all by hand (noticed the systemd conf and rsyslog conf).

Thanks.

**Comment by gusarg81** [comment]
Ok, web interface now loaded, I've loggued in. But no data, in references to my server (alread configured .rconrc). What I am missing?

**Comment by dieselburner** [comment]
What do you mean by "no data"? Please take into account I was developing this interface for Insurgency (not Sandstorm), so there might be some things to adapt, and I'm willing to help with that. A tip: dev mode in chrome could give you a hint in case of errors. Also, check the syslog logs of rcon-web backend.

**Comment by gusarg81** [comment]
Ok, didn't realized that is for the first version of the game.

By no data, means that every section has no data, or I am not sure what is supposed to have (Is like i am blind here, because there are zero docs of this project).

There is no errors on console from browser (I use Firefox) and also no errors on syslog, because also I don't see errrors on the site either.

Examples:

https://imgur.com/9uKyXDO
https://imgur.com/dZwtYMm
https://imgur.com/AyTQNJS
https://imgur.com/Wy9tXRR

**Comment by dieselburner** [comment]
Ok, let's do like this - please contact me directly via email - the reason is that if you could provide me with a rcon password, I could debug it tomorrow with you to solve what is missing to support Sandstorm, and then you can change the password once we're done. I don't want to provide my email here - please check the git log and write to me directly.

**Comment by gusarg81** [comment]
I am sorry, But I can' t do that. Thanks anyways!

**Comment by dieselburner** [comment]
No problem, if you have any questions - let me know. Otherwise, I will not be able to debug and implement support for Sandstorm without having a temporary RCON access. I'll have a look if I can set up the Sandstorm server by my own, but I do not have available hardware at the moment. One option would be having it running in a VM on my dev machine - I'll check that.

**Comment by dieselburner** [comment]
Closing. OP was able to build and run rcon-web, but the open question about Sandstorm support moved to #4.
